name = "french"
compatibility_date = "2024-01-01"
main = "dist/_worker.js"
assets = { directory = "dist", binding = "ASSETS" }

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "french-learning"
database_id = "24feb8bc-15d6-4c1f-9735-a613ee03bd68"
